import { lazy } from "react";

// Auto-extracted from App.jsx in PHASE12256.
// Purpose: reduce App.jsx loading/cognitive risk without changing route paths or behavior.

export const WellnessDashboard = lazy(() => import('../pages/WellnessDashboard'));

export const Login = lazy(() => import("../pages/Login.jsx"));
export const LoginCallback = lazy(() => import("../pages/LoginCallback.jsx"));
export const CanvaLanding = lazy(() => import("../pages/CanvaLanding.jsx"));
export const MeetLumi = lazy(() => import("../pages/MeetLumi.jsx"));
export const AdminLogin = lazy(() => import("../pages/AdminLogin.jsx"));
export const Start = lazy(() => import("../pages/Start.tsx"));
export const Register = lazy(() => import("../pages/Register.jsx"));
export const ForgotPassword = lazy(() => import("../pages/ForgotPassword.jsx"));
export const ResetPassword = lazy(() => import("../pages/ResetPassword.jsx"));
export const BlogEditor = lazy(() => import("../pages/BlogEditor.jsx"));
export const BlogPost = lazy(() => import("../pages/BlogPost.jsx"));
export const BlogIndex = lazy(() => import("../pages/BlogIndex.jsx"));
export const MoodPage = lazy(() => import("../pages/MoodPage.jsx"));
export const StatePage = lazy(() => import("../pages/StatePage.jsx"));
export const JournalPage = lazy(() => import("../pages/JournalPage.jsx"));
export const ReflectionPage = lazy(() => import("../pages/Reflection.jsx"));
export const DailyReflection = lazy(() => import("../pages/DailyReflection.jsx"));
export const AIChatPage = lazy(() => import("../pages/AIChatPage.tsx"));
export const Analytics = lazy(() => import("../pages/Analytics.jsx"));
export const CrisisResources = lazy(() => import("../pages/CrisisResources.jsx"));
export const Settings = lazy(() => import("../pages/Settings.jsx"));
export const ReminderScheduler = lazy(() => import("../components/ReminderScheduler.jsx"));
export const VoiceSettings = lazy(() => import("../components/VoiceSettings.jsx"));
export const Wellness = lazy(() => import("../pages/Wellness.jsx"));
export const AffirmationWall = lazy(() => import("../pages/AffirmationWall.jsx"));
export const TalkTopics = lazy(() => import("../pages/TalkTopics.jsx"));
export const Premium = lazy(() => import("../pages/Premium.jsx"));
export const SubscriberBenefitsPage = lazy(() => import("../pages/SubscriberBenefitsPage.jsx"));
export const Admin = lazy(() => import("../pages/Admin.jsx"));
export const Contact = lazy(() => import("../pages/Contact.jsx"));
export const FAQPage = lazy(() => import("../pages/FAQPage.jsx"));
export const Privacy = lazy(() => import("../pages/Privacy.jsx"));
export const Invite = lazy(() => import("../pages/Invite.jsx"));
export const Upgrade = lazy(() => import("../pages/Upgrade.jsx"));
export const Onboarding = lazy(() => import("../pages/Onboarding.tsx"));
export const OnboardingFlow = lazy(() => import("../pages/OnboardingFlow.jsx"));
export const AvatarLab = lazy(() => import("../pages/AvatarLab.jsx"));
export const RigLab = lazy(() => import("../pages/RigLab.jsx"));
export const MotionLab = lazy(() => import("../pages/MotionLab.jsx"));
export const Profile = lazy(() => import("../pages/Profile.jsx"));
export const DailyFlow = lazy(() => import("../features/daily/DailyFlow.tsx"));
export const MirrorPage = lazy(() => import("../pages/MirrorPage.tsx"));
export const DiscernmentDashboard = lazy(() => import("../pages/DiscernmentDashboard.jsx"));
export const ProtocolBrowser = lazy(() => import("../pages/ProtocolBrowser.jsx"));
export const ProtocolSession = lazy(() => import("../pages/ProtocolSession.jsx"));
export const BiometricDashboard = lazy(() => import("../pages/BiometricDashboard.jsx"));
export const AgentInteraction = lazy(() => import("../pages/AgentInteraction.jsx"));
export const WellnessToolsHub = lazy(() => import("../pages/WellnessToolsHub.jsx"));
export const DesignSystemV2 = lazy(() => import("../pages/DesignSystemV2.jsx"));
export const GAD7Assessment = lazy(() => import("../pages/tools/GAD7Assessment.jsx"));
export const PHQ9Assessment = lazy(() => import("../pages/tools/PHQ9Assessment.jsx"));
export const CognitiveDistortionChecker = lazy(() => import("../pages/tools/CognitiveDistortionChecker.jsx"));
export const BreathPacer = lazy(() => import("../pages/tools/BreathPacer.jsx"));
export const BoundaryBuilderTool = lazy(() => import("../pages/tools/BoundaryBuilderTool.jsx"));
export const ManipulationDetector = lazy(() => import("../pages/tools/ManipulationDetector.jsx"));
export const SleepQualityCalculator = lazy(() => import("../pages/tools/SleepQualityCalculator.jsx"));
export const NervousSystemCheck = lazy(() => import("../pages/tools/NervousSystemCheck.jsx"));
export const ToolsIndex = lazy(() => import("../pages/tools/index.jsx"));
export const CommunityPage = lazy(() => import("../pages/CommunityFeed.jsx"));
export const CommunityHub = lazy(() => import("../pages/CommunityHub.jsx"));
export const CommunityCircle = lazy(() => import("../pages/CommunityCircle.jsx"));
export const InsightsDashboard = lazy(() => import("../pages/InsightsDashboard.jsx"));
export const CelebrationRitual = lazy(() => import("../pages/CelebrationRitual.jsx"));
export const DiscussionPage = lazy(() => import("../features/community/DiscussionPage.jsx"));
export const ToolsPage = lazy(() => import("../pages/ToolsPage.jsx"));
export const BreathTool = lazy(() => import("../pages/tools/BreathTool.jsx"));
export const BreathingTool = lazy(() => import("../pages/tools/BreathingTool.jsx"));
export const CheckIn = lazy(() => import("../pages/CheckIn.jsx"));
export const CelebrationFlow = lazy(() => import("../pages/CelebrationFlow.jsx"));
export const LumiV6Preview = lazy(() => import("../pages/LumiV6Preview.jsx"));
export const DailyRitualPage = lazy(() => import("../pages/DailyRitualPage.tsx"));
export const WisdomToolsPage = lazy(() => import("../pages/WisdomToolsPage.tsx"));
export const AdvancedToolsPage = lazy(() => import("../pages/AdvancedToolsPage.tsx"));
export const MasteryToolsPage = lazy(() => import("../pages/MasteryToolsPage.tsx"));
export const AtlasDashboard = lazy(() => import("../pages/AtlasDashboard.tsx"));
export const StrategyMapsPage = lazy(() => import("../pages/StrategyMapsPage.tsx"));
export const CollaborativeLabPage = lazy(() => import("../pages/CollaborativeLabPage.tsx"));
export const ResilienceMetricsPage = lazy(() => import("../pages/ResilienceMetricsPage.tsx"));
export const AdaptiveCompanionPage = lazy(() => import("../pages/AdaptiveCompanionPage.tsx"));
export const KnowledgeSynthesisPage = lazy(() => import("../pages/KnowledgeSynthesisPage.tsx"));
export const WisdomPracticesPage = lazy(() => import("../pages/WisdomPracticesPage.tsx"));
export const GrowthAnalyticsPage = lazy(() => import("../pages/GrowthAnalyticsPage.tsx"));
export const DailyPracticePage = lazy(() => import("../pages/DailyPracticePage.jsx"));
export const RoutinesPage = lazy(() => import("../pages/RoutinesPage.jsx"));
export const GrowthPage = lazy(() => import("../pages/GrowthPage.jsx"));
export const PeacescapePage = lazy(() => import("../pages/PeacescapePage.jsx"));
export const RecoveryPage = lazy(() => import("../pages/RecoveryPage.jsx"));
export const SelfLovePage = lazy(() => import("../pages/SelfLovePage.jsx"));
export const SleepHubPage = lazy(() => import("../pages/hubs/SleepHubPage.jsx"));
export const BoundariesHubPage = lazy(() => import("../pages/hubs/BoundariesHubPage.jsx"));
export const SelfWorthHubPage = lazy(() => import("../pages/hubs/SelfWorthHubPage.jsx"));
export const ResilienceHubPage = lazy(() => import("../pages/hubs/ResilienceHubPage.jsx"));
export const AnxietyHubPage = lazy(() => import("../pages/hubs/AnxietyHubPage.jsx"));
export const RelationshipsHubPage = lazy(() => import("../pages/hubs/RelationshipsHubPage.jsx"));
export const GriefHubPage = lazy(() => import("../pages/hubs/GriefHubPage.jsx"));
export const SelfCompassionHubPage = lazy(() => import("../pages/hubs/SelfCompassionHubPage.jsx"));
export const MindfulnessHubPage = lazy(() => import("../pages/hubs/MindfulnessHubPage.jsx"));
export const StressHubPage = lazy(() => import("../pages/hubs/StressHubPage.jsx"));
export const TraumaHealingHubPage = lazy(() => import("../pages/hubs/TraumaHealingHubPage.jsx"));
export const EmotionalIntelligenceHubPage = lazy(() => import("../pages/hubs/EmotionalIntelligenceHubPage.jsx"));
export const PersonalGrowthHubPage = lazy(() => import("../pages/hubs/PersonalGrowthHubPage.jsx"));
export const InnerPeaceHubPage = lazy(() => import("../pages/hubs/InnerPeaceHubPage.jsx"));
export const HubsIndexPage = lazy(() => import("../pages/hubs/HubsIndexPage.jsx"));
export const HealingJourneyHubPage = lazy(() => import("../pages/hubs/HealingJourneyHubPage.jsx"));
export const SelfCareHubPage = lazy(() => import("../pages/hubs/SelfCareHubPage.jsx"));
export const CopingSkillsHubPage = lazy(() => import("../pages/hubs/CopingSkillsHubPage.jsx"));
export const InnerWorkHubPage = lazy(() => import("../pages/hubs/InnerWorkHubPage.jsx"));
export const BreathworkHubPage = lazy(() => import("../pages/hubs/BreathworkHubPage.jsx"));
export const JournalingHubPage = lazy(() => import("../pages/hubs/JournalingHubPage.jsx"));
export const BodyMindHubPage = lazy(() => import("../pages/hubs/BodyMindHubPage.jsx"));
export const DailyPracticeHubPage = lazy(() => import("../pages/hubs/DailyPracticeHubPage.jsx"));
export const GratitudeHubPage = lazy(() => import("../pages/hubs/GratitudeHubPage.jsx"));
export const GratitudePractice = lazy(() => import("../pages/GratitudePractice.jsx"));
export const LearnHub = lazy(() => import("../pages/LearnHub.jsx"));
export const LearnGuides = lazy(() => import("../pages/LearnGuides.jsx"));
export const LearnArticles = lazy(() => import("../pages/LearnArticles.jsx"));
export const LearnGuideDetail = lazy(() => import("../pages/LearnDetail.jsx").then(m => ({ default: m.LearnGuideDetail })));
export const LearnArticleDetail = lazy(() => import("../pages/LearnDetail.jsx").then(m => ({ default: m.LearnArticleDetail })));
export const ThoughtworkHubPage = lazy(() => import("../pages/hubs/ThoughtworkHubPage.jsx"));
export const LifePurposeHubPage = lazy(() => import("../pages/hubs/LifePurposeHubPage.jsx"));
export const CommunicationHubPage = lazy(() => import("../pages/hubs/CommunicationHubPage.jsx"));
export const ForgivenessHubPage = lazy(() => import("../pages/hubs/ForgivenessHubPage.jsx"));
export const EnergyManagementHubPage = lazy(() => import("../pages/hubs/EnergyManagementHubPage.jsx"));
export const HabitsHubPage = lazy(() => 
import("../pages/hubs/HabitsHubPage.jsx"));
export const ConfidenceHubPage = lazy(() => import("../pages/hubs/ConfidenceHubPage.jsx"));
export const AboutPage = lazy(() => import("../pages/About.jsx"));
export const FeaturesPage = lazy(() => import("../pages/Features.jsx"));
export const HealingPage = lazy(() => import("../pages/Healing.jsx"));
export const WellbeingPage = lazy(() => import("../pages/Wellbeing.jsx"));
export const MentalWellnessPage = lazy(() => import("../pages/MentalWellness.jsx"));
export const SelfLoveCanonical = lazy(() => import("../pages/SelfLove.jsx"));
export const GrowthCanonical = lazy(() => import("../pages/Growth.jsx"));
export const MindfulnessCanonical = lazy(() => import("../pages/Mindfulness.jsx"));
export const ResilienceCanonical = lazy(() => import("../pages/Resilience.jsx"));
export const AnxietyCanonical = lazy(() => import("../pages/Anxiety.jsx"));
export const DepressionCanonical = lazy(() => import("../pages/Depression.jsx"));
export const TrustCenterPage = lazy(() =>
  import("../pages/trust/TrustCenterPage.jsx")
);
export const AITransparencyPage = lazy(() =>
  import("../pages/trust/AITransparencyPage.jsx")
);
export const FocusHubPage = lazy(() => import("../pages/hubs/FocusHubPage.jsx"));
export const SpiritualityHubPage = lazy(() => import("../pages/hubs/SpiritualityHubPage.jsx"));
export const MotivationHubPage = lazy(() => import("../pages/hubs/MotivationHubPage.jsx"));
export const AcceptanceHubPage = lazy(() => import("../pages/hubs/AcceptanceHubPage.jsx"));
export const CreativityHubPage = lazy(() => import("../pages/hubs/CreativityHubPage.jsx"));
export const SelfAwarenessHubPage = lazy(() => import("../pages/hubs/SelfAwarenessHubPage.jsx"));
export const NervousSystemHubPage = lazy(() => import("../pages/hubs/NervousSystemHubPage.jsx"));
export const PresenceHubPage = lazy(() => import("../pages/hubs/PresenceHubPage.jsx"));
export const WisdomHubPage = lazy(() => import("../pages/hubs/WisdomHubPage.jsx"));
export const SelfDiscoveryHubPage = lazy(() => import("../pages/hubs/SelfDiscoveryHubPage.jsx"));
export const TwelvePracticesPage = lazy(() => import("../pages/TwelvePracticesPage.jsx"));
export const GuidedJournalingPage = lazy(() => import("../pages/GuidedJournalingPage.tsx"));
export const InsightCardsPage = lazy(() => import("../pages/InsightCardsPage.tsx"));
export const ProgressDashboardPage = lazy(() => import("../pages/ProgressDashboardPage.tsx"));
export const WisdomSynthesisPage = lazy(() => import("../pages/WisdomSynthesisPage.tsx"));
export const CognitiveArchitecturePage = lazy(() => import("../pages/CognitiveArchitecturePage.tsx"));
export const PhilosophicalInquiryPage = lazy(() => import("../pages/PhilosophicalInquiryPage.tsx"));
export const DailyWisdomOraclePage = lazy(() => import("../pages/DailyWisdomOraclePage.tsx"));
export const SystemsThinkingPage = lazy(() => import("../pages/SystemsThinkingPage.tsx"));
export const MetaLearningPage = lazy(() => import("../pages/MetaLearningPage.tsx"));
export const ContentStudioPage = lazy(() => import("../pages/ContentStudioPage.tsx"));
export const StudyVaultPage = lazy(() => import("../pages/StudyVaultPage.jsx"));
export const EliteToolsDashboard = lazy(() => import("../pages/EliteToolsDashboard.tsx"));
export const ContentAdminDashboard = lazy(() => import("../pages/ContentAdminDashboard.jsx"));
export const CRMPage = lazy(() => import("../pages/CRMPage.jsx"));
export const DashboardOverview = lazy(() => import("../pages/dashboard/Overview.jsx"));
export const AdminCommandCenter = lazy(() => import("../pages/admin/CommandCenter.jsx"));
export const AdminHealthDashboard = lazy(() => import("../pages/admin/HealthDashboard.jsx"));
export const SocialDashboard = lazy(() => import("../pages/admin/SocialDashboard.jsx"));
export const NarrativeOpsConsole = lazy(() => import("../pages/admin/NarrativeOpsConsole.jsx"));
export const AdminSocial = lazy(() => import("../pages/admin/AdminSocial.jsx"));
export const SocialGenerator = lazy(() => import("../pages/admin/SocialGenerator.jsx"));
export const SocialLibrary = lazy(() => import("../pages/admin/SocialLibrary.jsx"));
export const SocialCalendar = lazy(() => import("../pages/admin/SocialCalendar.jsx"));
export const SocialAnalytics = lazy(() => import("../pages/admin/SocialAnalytics.jsx"));
export const SocialHub = lazy(() => import("../pages/SocialHub.jsx"));
export const BillingViewer = lazy(() => import("../pages/admin/BillingViewer.jsx"));
export const Sessions = lazy(() => import("../pages/account/Sessions.jsx"));
export const DeleteAccount = lazy(() => import("../pages/account/DeleteAccount.jsx"));
export const AccountProfile = lazy(() => import("../pages/account/Profile.jsx"));
export const AccountSecurity = lazy(() => import("../pages/account/Security.jsx"));
export const AccountBilling = lazy(() => import("../pages/account/Billing.jsx"));
export const ValuesFinderPage = lazy(() => import("../pages/ValuesFinderPage.jsx"));
export const ValuesPage = lazy(() => import("../pages/ValuesPage.jsx"));
export const AboutApproachPage = lazy(() => import("../pages/AboutApproachPage.jsx"));
export const BoundariesPage = lazy(() => import("../pages/BoundariesPage.jsx"));
export const MovementSnacksPage = lazy(() => import("../pages/MovementSnacksPage.jsx"));
export const CoherenceLadderPage = lazy(() => import("../pages/CoherenceLadderPage.jsx"));
export const PerceptionRefinementPage = lazy(() => import("../pages/PerceptionRefinementPage.jsx"));
export const NervousSystemFloodingPage = lazy(() => import("../pages/NervousSystemFloodingPage.jsx"));
export const PermacultureWellnessPage = lazy(() => import("../pages/PermacultureWellnessPage.jsx"));
export const SelfWorthReflectionPage = lazy(() => import("../pages/SelfWorthReflectionPage.jsx"));
export const Challenge = lazy(() => import("../pages/Challenge.jsx"));
export const ChallengeDay = lazy(() => import("../pages/ChallengeDay.jsx"));
export const AlignmentPath = lazy(() => import("../pages/AlignmentPath.jsx"));
export const SystemMapPage = lazy(() => import("../pages/SystemMapPage.jsx"));
export const ReframePage = lazy(() => import("../pages/tools/ReframePage.jsx"));
export const TwelveStepsPage = lazy(() => import("../pages/TwelveStepsPage.tsx"));
export const BehaviorChangePage = lazy(() => import("../pages/BehaviorChangePage.tsx"));
export const SavedLibrary = lazy(() => import("../pages/library/SavedLibrary.jsx"));
export const GentleProgressDashboard = lazy(() => import("../pages/dashboard/ProgressDashboard.jsx"));
export const TopicHubPage = lazy(() => import("../pages/hubs/TopicHubPage.jsx"));

// Batch 11 - Personalization (P201-P210)
export const PathwaysHome = lazy(() => import("../pages/pathways/PathwaysHome.jsx"));
export const GoalOnboarding = lazy(() => import("../pages/pathways/GoalOnboarding.jsx"));
export const Favorites = lazy(() => import("../pages/pathways/Favorites.jsx"));
export const ProgressStreaks = lazy(() => import("../pages/pathways/ProgressStreaks.jsx"));
export const CalmPlan = lazy(() => import("../pages/pathways/CalmPlan.jsx"));
export const ValuesToActions = lazy(() => import("../pages/pathways/ValuesToActions.jsx"));
export const ReflectionHistory = lazy(() => import("../pages/pathways/ReflectionHistory.jsx"));
export const NotificationPreferences = lazy(() => import("../pages/preferences/NotificationPreferences.jsx"));
export const SafetyPreferences = lazy(() => import("../pages/preferences/SafetyPreferences.jsx"));

// Batch 11 - Tools Expansion (P211-P220)
export const CompassionBreak = lazy(() => import("../pages/tools/CompassionBreak.jsx"));
export const Reframe = lazy(() => import("../pages/tools/Reframe.jsx"));
export const UrgeSurf = lazy(() => import("../pages/tools/UrgeSurf.jsx"));
export const GriefLetter = lazy(() => import("../pages/tools/GriefLetter.jsx"));
export const RepairScript = lazy(() => import("../pages/tools/RepairScript.jsx"));
export const AweMicrodose = lazy(() => import("../pages/tools/AweMicrodose.jsx"));
export const BodyScan = lazy(() => import("../pages/tools/BodyScan.jsx"));
export const DigitalSunset = lazy(() => import("../pages/tools/DigitalSunset.jsx"));
export const MeaningMap = lazy(() => import("../pages/tools/MeaningMap.jsx"));
export const CommunityCheckin = lazy(() => import("../pages/tools/CommunityCheckin.jsx"));

// Batch 11 - Admin & Content (P221-P240)
export const ContentStudioAdmin = lazy(() => import("../pages/admin/ContentStudioAdmin.jsx"));
export const SocialStudioAdmin = lazy(() => import("../pages/admin/SocialStudioAdmin.jsx"));
export const NewsletterAdmin = lazy(() => import("../pages/admin/NewsletterAdmin.jsx"));
export const AdminPublishing = lazy(() => import("../pages/admin/AdminPublishing.jsx"));
export const AdminPublishingToday = lazy(() => import("../pages/admin/AdminPublishingToday.jsx"));
export const BlogDraftViewer = lazy(() => import("../pages/BlogDraftViewer.jsx"));
export const RevenueAdmin = lazy(() => import("../pages/admin/RevenueAdmin.jsx"));

// Batch 11 - Account & Payments (P241-P250)
export const Subscription = lazy(() => import("../pages/account/Subscription.jsx"));
export const OrderHistory = lazy(() => import("../pages/account/OrderHistory.jsx"));
export const PricingPage = lazy(() => import("../pages/PricingPage.jsx"));
export const PricingReal = lazy(() => import("../pages/Pricing.jsx"));
export const RefundHelp = lazy(() => import("../pages/help/RefundHelp.jsx"));
export const LegalPage = lazy(() => import("../pages/LegalPage.jsx"));

// Batch 14 - Trust, Safety, Community, Learning (P351-P400)
export const SafetyCenter = lazy(() => import("../pages/SafetyCenter.jsx"));
export const DataRetention = lazy(() => import("../pages/DataRetention.jsx"));
export const CommunityGuidelines = lazy(() => import("../pages/CommunityGuidelines.jsx"));
export const PublicRoadmap = lazy(() => import("../pages/PublicRoadmap.jsx"));
export const CreatorProfile = lazy(() => import("../pages/CreatorProfile.jsx"));
export const PressKit = lazy(() => import("../pages/PressKit.jsx"));
export const CourseCatalog = lazy(() => import("../pages/CourseCatalog.jsx"));
export const PracticeLibrary = lazy(() => import("../pages/PracticeLibrary.jsx"));
export const RolesPermissions = lazy(() => import("../pages/admin/RolesPermissions.jsx"));

// Batch 15 - Optimization + Admin Tools (P401-P450)
export const FeatureFlags = lazy(() => import("../pages/admin/FeatureFlags.jsx"));
export const SystemAlerts = lazy(() => import("../pages/admin/SystemAlerts.jsx"));
export const FeedbackAggregator = lazy(() => import("../pages/admin/FeedbackAggregator.jsx"));
export const NarrativeDrafts = lazy(() => import("../pages/admin/NarrativeDrafts.jsx"));
export const SecurityDashboard = lazy(() => import("../pages/admin/SecurityDashboard.jsx"));
export const AuditLogExplorer = lazy(() => import("../pages/admin/AuditLogExplorer.jsx"));

// Batch 16 - Analytics, Community, Personalization, Wellness (P451-P500)
export const EngagementDashboard = lazy(() => import("../pages/admin/EngagementDashboard.jsx"));
export const AdminUsers = lazy(() => import("../pages/admin/AdminUsers.jsx"));
export const AdminTools = lazy(() => import("../pages/admin/AdminTools.jsx"));
export const UserProfile = lazy(() => import("../pages/UserProfile.jsx"));
export const WellnessGoals = lazy(() => import("../pages/WellnessGoals.jsx"));
export const MeditationPlayer = lazy(() => import("../pages/tools/MeditationPlayer.jsx"));
export const EmotionWheel = lazy(() => import("../pages/tools/EmotionWheel.jsx"));
export const EmailDigest = lazy(() => import("../pages/settings/EmailDigest.jsx"));

// Batch 17 - Content, Engagement, AI, A11y, Performance (P501-P550)
export const AIPersonality = lazy(() => import("../pages/settings/AIPersonality.jsx"));
export const WeeklyReflection = lazy(() => import("../pages/tools/WeeklyReflection.jsx"));
export const Presence = lazy(() => import("../pages/Presence.jsx"));
