export const canonicalNavItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Features", href: "/features" },
  { label: "Healing", href: "/healing" },
  { label: "Wellbeing", href: "/wellbeing" },
  { label: "Mental Wellness", href: "/mental-wellness" },
  { label: "Self Love", href: "/self-love" },
  { label: "Growth", href: "/growth" },
  { label: "Anxiety", href: "/anxiety" },
  { label: "Depression", href: "/depression" },
  { label: "Resilience", href: "/resilience" },
  { label: "Mindfulness", href: "/mindfulness" },
  { label: "Tools", href: "/tools/all" },
  { label: "Wellness Tools", href: "/wellness-tools-hub" },
  { label: "Journal", href: "/journal" },
  { label: "Chat", href: "/chat" },
  { label: "Privacy", href: "/privacy" },
];
