-- Optimized Database Indexes for Maximum Performance
-- Generated by Evolution Engine v1.0.3

-- User table indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_stripe_customer_id ON users(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_users_subscription_tier ON users(subscription_tier);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);

-- Healing messages indexes for AI chat performance
CREATE INDEX IF NOT EXISTS idx_healing_messages_user_id ON healing_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_healing_messages_session_id ON healing_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_healing_messages_timestamp ON healing_messages(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_healing_messages_user_session ON healing_messages(user_id, session_id);
CREATE INDEX IF NOT EXISTS idx_healing_messages_emotion ON healing_messages(emotion) WHERE emotion IS NOT NULL;

-- Sessions index for fast session lookups
CREATE INDEX IF NOT EXISTS idx_sessions_expire ON sessions(expire);

-- Billing transactions indexes
CREATE INDEX IF NOT EXISTS idx_billing_transactions_user_id ON billing_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_billing_transactions_stripe_session_id ON billing_transactions(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_billing_transactions_created_at ON billing_transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_transactions_status ON billing_transactions(status);

-- Analytics events indexes for reporting
CREATE INDEX IF NOT EXISTS idx_analytics_events_user_id ON analytics_events(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_type ON analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_timestamp ON analytics_events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events_session_id ON analytics_events(session_id);

-- Assessments indexes
CREATE INDEX IF NOT EXISTS idx_assessments_user_id ON assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_assessments_type ON assessments(type);
CREATE INDEX IF NOT EXISTS idx_assessments_completed_at ON assessments(completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_assessments_follow_up_date ON assessments(follow_up_date) WHERE follow_up_date IS NOT NULL;

-- System logs indexes
CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_timestamp ON system_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_source ON system_logs(source);

-- Services monitoring
CREATE INDEX IF NOT EXISTS idx_services_status ON services(status);
CREATE INDEX IF NOT EXISTS idx_services_last_checked ON services(last_checked DESC);

-- Composite indexes for complex queries
CREATE INDEX IF NOT EXISTS idx_users_subscription_composite ON users(subscription_tier, subscription_status, subscription_end_date);
CREATE INDEX IF NOT EXISTS idx_healing_messages_ai_analytics ON healing_messages(user_id, timestamp DESC, is_helpful);
CREATE INDEX IF NOT EXISTS idx_billing_composite ON billing_transactions(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_composite ON analytics_events(user_id, event_type, timestamp DESC);

-- Function-based indexes for optimized queries
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users(LOWER(email));
CREATE INDEX IF NOT EXISTS idx_users_active_premium ON users(subscription_tier) WHERE is_active = true AND subscription_tier != 'free';

-- Partial indexes for filtered queries
CREATE INDEX IF NOT EXISTS idx_active_users ON users(created_at DESC) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_helpful_messages ON healing_messages(user_id, timestamp DESC) WHERE is_helpful = true;
CREATE INDEX IF NOT EXISTS idx_successful_transactions ON billing_transactions(user_id, created_at DESC) WHERE status = 'completed';

ANALYZE;
