import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from '@/components/Card';
import { Badge } from '@/components/Badge';
import { TrendingUp, TrendingDown, Eye, Heart, Share2, MessageCircle } from 'lucide-react';
/**
 * Analytics Dashboard Component
 * Displays engagement metrics and trends
 */
export function AnalyticsDashboard({ data, period = '30d' }) {
    const renderMetricCard = (title, value, change, icon, testId) => {
        const isPositive = change >= 0;
        return (_jsxs(Card, { className: "p-6", "data-testid": testId, children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsx("div", { className: "text-sm font-medium text-muted-foreground", children: title }), _jsx("div", { className: "p-2 bg-primary/10 rounded-lg", children: icon })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "text-3xl font-bold", "data-testid": `${testId}-value`, children: value.toLocaleString() }), _jsxs("div", { className: "flex items-center gap-2", children: [isPositive ? (_jsx(TrendingUp, { className: "h-4 w-4 text-green-600" })) : (_jsx(TrendingDown, { className: "h-4 w-4 text-red-600" })), _jsxs("span", { className: `text-sm font-medium ${isPositive ? 'text-green-600' : 'text-red-600'}`, "data-testid": `${testId}-change`, children: [isPositive ? '+' : '', change, "%"] }), _jsxs("span", { className: "text-sm text-muted-foreground", children: ["vs last ", period] })] })] })] }));
    };
    return (_jsxs("div", { "data-testid": "analytics-dashboard", children: [_jsx("div", { className: "mb-6", children: _jsx("div", { className: "inline-flex gap-2 p-1 bg-muted rounded-lg", children: ['7d', '30d', '90d'].map((p) => (_jsxs(Badge, { variant: period === p ? 'primary' : 'gray', className: "cursor-pointer", "data-testid": `badge-period-${p}`, children: [p === '7d' && '7 Days', p === '30d' && '30 Days', p === '90d' && '90 Days'] }, p))) }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: [renderMetricCard('Total Views', data.views.value, data.views.change, _jsx(Eye, { className: "h-5 w-5 text-primary" }), 'metric-views'), renderMetricCard('Engagement Rate', data.engagement.value, data.engagement.change, _jsx(Heart, { className: "h-5 w-5 text-primary" }), 'metric-engagement'), renderMetricCard('Shares', data.shares.value, data.shares.change, _jsx(Share2, { className: "h-5 w-5 text-primary" }), 'metric-shares'), renderMetricCard('Comments', data.comments.value, data.comments.change, _jsx(MessageCircle, { className: "h-5 w-5 text-primary" }), 'metric-comments')] }), _jsxs(Card, { className: "p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", "data-testid": "text-top-content", children: "Top Performing Content" }), _jsx("div", { className: "space-y-4", children: [
                            { title: '5 Mindfulness Exercises', views: 12500, engagement: 8.5 },
                            { title: 'Understanding Anxiety', views: 9800, engagement: 7.2 },
                            { title: 'Stress Relief Techniques', views: 8200, engagement: 6.8 },
                        ].map((content, i) => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-muted rounded-lg", "data-testid": `top-content-${i}`, children: [_jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-medium", children: content.title }), _jsxs("div", { className: "text-sm text-muted-foreground", children: [content.views.toLocaleString(), " views \u2022 ", content.engagement, "% engagement"] })] }), _jsxs(Badge, { variant: "primary", children: ["# ", i + 1] })] }, i))) })] }), _jsxs(Card, { className: "p-6 mt-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: "Engagement Over Time" }), _jsx("div", { className: "h-64 flex items-center justify-center bg-muted rounded-lg", children: _jsxs("div", { className: "text-center text-muted-foreground", children: [_jsx(TrendingUp, { className: "h-12 w-12 mx-auto mb-2" }), _jsx("p", { children: "Chart visualization will appear here" }), _jsx("p", { className: "text-sm", children: "Line chart showing engagement trends" })] }) })] })] }));
}
