export async function exportToPdf(content, filename = "export.pdf") {
  const printWindow = window.open("", "_blank");
  
  if (!printWindow) {
    throw new Error("Could not open print window. Please allow popups.");
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        @page {
          margin: 1in;
          size: letter;
        }
        body {
          font-family: Georgia, serif;
          font-size: 12pt;
          line-height: 1.6;
          color: #1a1a1a;
          max-width: 6.5in;
          margin: 0 auto;
          padding: 20px;
        }
        h1 {
          font-size: 24pt;
          color: #0d9488;
          margin-bottom: 0.5em;
          border-bottom: 2px solid #0d9488;
          padding-bottom: 0.3em;
        }
        h2 {
          font-size: 18pt;
          color: #1e3a3a;
          margin-top: 1.5em;
        }
        h3 {
          font-size: 14pt;
          color: #374151;
        }
        p {
          margin-bottom: 1em;
          text-align: justify;
        }
        .date {
          color: #6b7280;
          font-size: 10pt;
          margin-bottom: 2em;
        }
        .footer {
          position: fixed;
          bottom: 0.5in;
          left: 0;
          right: 0;
          text-align: center;
          font-size: 9pt;
          color: #9ca3af;
        }
        blockquote {
          border-left: 3px solid #0d9488;
          padding-left: 1em;
          margin-left: 0;
          color: #4b5563;
          font-style: italic;
        }
        ul, ol {
          margin-bottom: 1em;
          padding-left: 1.5em;
        }
        li {
          margin-bottom: 0.3em;
        }
        @media print {
          body {
            padding: 0;
          }
          .no-print {
            display: none;
          }
        }
      </style>
    </head>
    <body>
      <div class="date">${new Date().toLocaleDateString("en-US", { 
        weekday: "long", 
        year: "numeric", 
        month: "long", 
        day: "numeric" 
      })}</div>
      ${content}
      <div class="footer">
        Generated by The Genuine Love Project
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  return true;
}

export function formatJournalForPdf(journal) {
  const date = new Date(journal.createdAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric"
  });

  return `
    <h1>${journal.title || "Journal Entry"}</h1>
    <p class="date">Written on ${date}</p>
    ${journal.prompt ? `<blockquote>${journal.prompt}</blockquote>` : ""}
    <div>${journal.content.replace(/\n/g, "<br>")}</div>
    ${journal.mood ? `<p><strong>Mood:</strong> ${journal.mood}</p>` : ""}
    ${journal.tags?.length ? `<p><strong>Tags:</strong> ${journal.tags.join(", ")}</p>` : ""}
  `;
}

export function formatReflectionForPdf(reflection) {
  return `
    <h1>Reflection</h1>
    <h2>${reflection.title || "My Reflection"}</h2>
    <div>${reflection.content.replace(/\n/g, "<br>")}</div>
    ${reflection.insights ? `
      <h3>Key Insights</h3>
      <ul>
        ${reflection.insights.map(i => `<li>${i}</li>`).join("")}
      </ul>
    ` : ""}
  `;
}
