import {
  Brain, Heart, Compass, Wind, Shield, ShieldAlert, Moon, Activity,
} from "lucide-react";

export const TOOLS = [
  {
    slug: "anxiety-assessment",
    href: "/tools/gad7",
    title: "Anxiety Self-Assessment (GAD-7)",
    description: "Clinically inspired 7-question anxiety check-in. Takes about 2 minutes.",
    category: "Assessment",
    estimatedTime: "2 min",
    keywordTarget: "anxiety test online",
    icon: Brain,
    color: "from-amber-500 to-orange-500",
    testid: "tool-anxiety-assessment",
  },
  {
    slug: "depression-screening",
    href: "/tools/phq9",
    title: "Depression Screening (PHQ-9)",
    description: "The same 9-question screener used in many clinics. Private and immediate results.",
    category: "Assessment",
    estimatedTime: "3 min",
    keywordTarget: "depression test",
    icon: Heart,
    color: "from-rose-500 to-pink-500",
    testid: "tool-depression-screening",
  },
  {
    slug: "cognitive-distortion-checker",
    href: "/tools/distortion-checker",
    title: "Cognitive Distortion Checker",
    description: "Paste any thought or message. We gently identify thinking traps and offer a reframe.",
    category: "Cognitive",
    estimatedTime: "30 sec",
    keywordTarget: "cognitive distortions test",
    icon: Compass,
    color: "from-purple-500 to-indigo-500",
    testid: "tool-cognitive-distortion-checker",
  },
  {
    slug: "manipulation-detector",
    href: "/tools/manipulation-detector",
    title: "Manipulation Detector",
    description: "Paste a message or short exchange. Spot common manipulation tactics with gentle reframes.",
    category: "Awareness",
    estimatedTime: "30 sec",
    keywordTarget: "am I being manipulated",
    icon: ShieldAlert,
    color: "from-rose-500 to-amber-500",
    testid: "tool-manipulation-detector",
  },
  {
    slug: "breath-pacer",
    href: "/tools/breath-pacer",
    title: "Breathing Exercise Pacer",
    description: "Science-backed breath pacing for anxiety, sleep, and nervous-system regulation.",
    category: "Somatic",
    estimatedTime: "3\u201310 min",
    keywordTarget: "breathing exercise for anxiety",
    icon: Wind,
    color: "from-teal-500 to-cyan-500",
    testid: "tool-breath-pacer",
  },
  {
    slug: "boundary-builder",
    href: "/tools/boundary-builder",
    title: "Boundary Script Generator",
    description: "Answer a few questions. Get a personalized, compassionate boundary script you can practice.",
    category: "Relational",
    estimatedTime: "2 min",
    keywordTarget: "how to set boundaries",
    icon: Shield,
    color: "from-emerald-500 to-teal-500",
    testid: "tool-boundary-builder",
  },
  {
    slug: "sleep-quality-calculator",
    href: "/tools/sleep-quality-calculator",
    title: "Sleep Quality Self-Check",
    description: "Assess your sleep over the last week and get evidence-informed CBT-I-style suggestions.",
    category: "Assessment",
    estimatedTime: "3 min",
    keywordTarget: "sleep quality test",
    icon: Moon,
    color: "from-indigo-500 to-slate-500",
    testid: "tool-sleep-quality-calculator",
  },
  {
    slug: "nervous-system-check",
    href: "/tools/nervous-system-check",
    title: "Nervous System State Check",
    description: "A polyvagal-informed self-check: are you in safe, mobilized, or shut-down mode right now?",
    category: "Somatic",
    estimatedTime: "3 min",
    keywordTarget: "nervous system regulation test",
    icon: Activity,
    color: "from-teal-500 to-emerald-500",
    testid: "tool-nervous-system-check",
  },
];
