export const OFFICIAL_LUMI_VARIANTS = {
	LUMI_SOFT_PRESENCE: "LUMI_SOFT_PRESENCE",
	LUMI_CALM_GUIDE: "LUMI_CALM_GUIDE",
	LUMI_SLEEPY: "LUMI_SLEEPY",
	LUMI_GROUNDING: "LUMI_GROUNDING",
	LUMI_JOY: "LUMI_JOY",
	LUMI_REFLECTIVE: "LUMI_REFLECTIVE",
};