// @generated
/**
 * Auto-generated dynamic page for route: /blog/:slug
 * Parameter: slug
 * Generated by: scripts/generate-pages.mjs
 */
import { useParams } from 'wouter';
import ConfigRoute from '../pages/_autopilot.jsx';
import { SEO } from "../../components/SEO";
import SafetyFooter from "../../components/ui/SafetyFooter";

export default function BlogPage() {
  const params = useParams();
  return <ConfigRoute route="/blog/:slug" params={params} />;
}
