// @generated
/**
 * Auto-generated page for route: /forgot-password
 * Generated by: scripts/generate-pages.mjs
 * DO NOT EDIT - Changes will be overwritten on regeneration
 */
import ConfigRoute from '../pages/_autopilot.jsx';

export default function ForgotPasswordPage() {
  return <ConfigRoute route="/forgot-password" />;
}
