// @generated
/**
 * Auto-generated page for route: /healing-test
 * Generated by: scripts/generate-pages.mjs
 * DO NOT EDIT - Changes will be overwritten on regeneration
 */
import ConfigRoute from '../pages/_autopilot.jsx';
import { SEO } from "@/components/SEO";
import SafetyFooter from "@/components/ui/SafetyFooter";

export default function HealingTestPage() {
  return <ConfigRoute route="/healing-test" />;
}
