// @generated
/**
 * Auto-generated page for route: /healing
 * Generated by: scripts/generate-pages.mjs
 * DO NOT EDIT - Changes will be overwritten on regeneration
 */
import ConfigRoute from '../pages/_autopilot.jsx';

export default function HealingPage() {
  return <ConfigRoute route="/healing" />;
}
