// @generated
/**
 * Auto-generated page for route: /landing
 * Generated by: scripts/generate-pages.mjs
 * DO NOT EDIT - Changes will be overwritten on regeneration
 */
import ConfigRoute from '../pages/_autopilot.jsx';

export default function LandingPage() {
  return <ConfigRoute route="/landing" />;
}
