import { SEO } from "@/components/SEO";
import SafetyFooter from "@/components/ui/SafetyFooter";
// @generated
/**
 * Server-side redirect for alias route: /welcome → /
 * Generated by: scripts/generate-pages.mjs
 * 
 * This page implements a permanent (301) server-side redirect.
 * The redirect is handled by Express middleware before this component loads.
 * This file exists for documentation and fallback purposes.
 */

export function getServerSideProps() {
  return {
    redirect: {
      destination: '/',
      permanent: true
    }
  };
}

export default function WelcomeRedirect() {
  return (
    <div className="min-h-screen safe-padding hero-gradient">
      <SEO title="welcome — The Genuine Love Project" description="Welcome to your wellness journey." />
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4">welcome</h1>
        <p className="text-muted-foreground mb-8">
          This page is being refined. Use the navigation to explore tools while we finish this section.
        </p>
        <SafetyFooter />
      </main>
    </div>
  );
}
